### ISSUE TITLE
Plugin won't load

### ISSUE THREAD

**Issue by jschpp** [mumble-voip/mumble-json-bridge#7]
I've compiled this and tried to load the plugin into mumble.
I get the error message

```plain
Unable to load plugin "json_bridge_plugin.dll" - check the plugin interface!
```

Commands used to compile:
```plain
cmake -S . -B .\build\ -DCMAKE_TOOLCHAIN_FILE=D:/Source/vcpkg/scripts/buildsystems/vcpkg.cmake
cmake --build .\build\
```

I have no idea how to get more logs/info to debug this error

mumble version: 1.4.230
Windows version: 21H2 Build 19044.1766
Build Engine Version: 16.10.1+2fd48ab73
cmake version: 3.23.1
vcpkg version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e

**Comment by Krzmbrzl** [comment]
If you are also compiling Mumble yourself, you can get extended error information when compiling it with the [plugin-debug](https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/cmake_options.md#plugin-debug) flag set to `ON` like so:
```
cmake -Dplugin-debug=ON
```
Then you should get some command-line output describing the details of which functions were found and which are missing. The same info should then also be available via Mumble's [developer console](https://github.com/mumble-voip/mumble/blob/master/docs/DeveloperConsole.md).

**Comment by Krzmbrzl** [comment]
Another thing to check is how you linked against Boost. On Windows in particular it is very easy to link to Boost dynamically but by not having the respective Boost libraries in the system's search path will cause these libraries to not be found when attempting to load the plugin, so that said loading will fail.
That's why I usually advice to link against Boost statically when dealing with Windows.

**Comment by Krzmbrzl** [comment]
Closing this as fixed
